"""Weak topic detection from quiz history.

Quiz attempts are aggregated per topic: a topic is *weak* when the student's
accuracy stays below :data:`WEAK_THRESHOLD`.  Quizzes generated by the LLM tag
each question with a topic (the nearest heading or the topic the user asked
for), so this module only needs the stored results.
"""

from __future__ import annotations

import logging
import re
from collections import defaultdict
from typing import Any

from backend.utils import db

LOGGER = logging.getLogger(__name__)

#: Accuracy (0-1) under which a topic is considered weak.
WEAK_THRESHOLD = 0.6
#: Attempts needed before a topic is trusted enough to report.
MIN_ATTEMPTS = 1
#: Topics are matched case-insensitively; punctuation is stripped.
_TOPIC_CLEAN_RE = re.compile(r"[^a-z0-9 ]+")


def normalise_topic(topic: str | None) -> str:
    """Return a comparable topic key (lowercase, no punctuation)."""
    text = _TOPIC_CLEAN_RE.sub(" ", (topic or "").lower())
    return " ".join(text.split())


def topic_display_name(topic: str) -> str:
    """Turn a normalised key back into a readable label."""
    return topic.replace(" ", " ").strip().title() if topic else "General"


def compute_topic_accuracy(results: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Aggregate per-question outcomes into per-topic accuracy rows.

    Args:
        results: Rows from :func:`backend.utils.db.list_quiz_results`.

    Returns:
        ``[{"topic", "correct", "total", "accuracy"}]`` sorted worst-first.
    """
    totals: dict[str, list[int]] = defaultdict(lambda: [0, 0])  # topic -> [right, seen]

    for result in results:
        details = result.get("details") or []
        for item in details:
            topic = normalise_topic(item.get("topic") or "general") or "general"
            totals[topic][1] += 1
            if item.get("is_correct"):
                totals[topic][0] += 1

    rows = [
        {
            "topic": topic_display_name(topic),
            "topic_key": topic,
            "correct": counts[0],
            "total": counts[1],
            "accuracy": round(counts[0] / counts[1], 4) if counts[1] else 0.0,
        }
        for topic, counts in totals.items()
        if counts[1] >= MIN_ATTEMPTS
    ]
    rows.sort(key=lambda row: row["accuracy"])
    return rows


def get_weak_topics(doc_id: str, threshold: float = WEAK_THRESHOLD) -> list[str]:
    """Return the readable names of weak topics for a document."""
    rows = compute_topic_accuracy(db.list_quiz_results(doc_id))
    return [row["topic"] for row in rows if row["accuracy"] < threshold]


def weak_topics_report(doc_id: str, threshold: float = WEAK_THRESHOLD) -> dict[str, Any]:
    """Return the full weak-topic analysis payload used by ``GET /weak-topics``.

    Args:
        doc_id: Document identifier.
        threshold: Accuracy under which a topic counts as weak.

    Returns:
        ``{"attempts", "average_score", "topics", "weak_topics"}``.
    """
    results = db.list_quiz_results(doc_id)
    topics = compute_topic_accuracy(results)
    total_possible = sum(result.get("total", 0) for result in results)
    total_scored = sum(result.get("score", 0) for result in results)
    average = round(total_scored / total_possible, 4) if total_possible else 0.0

    weak = [row["topic"] for row in topics if row["accuracy"] < threshold]
    LOGGER.info(
        "Weak topics for %s: %s (attempts=%d)", doc_id, ", ".join(weak) or "none",
        len(results),
    )
    return {
        "doc_id": doc_id,
        "attempts": len(results),
        "average_score": average,
        "topics": topics,
        "weak_topics": weak,
    }