"""Pydantic request/response schemas for the IntelliPDF API."""

from backend.models.schemas import (  # noqa: F401
    AskRequest,
    AskResponse,
    DocumentInfo,
    EvaluateRequest,
    EvaluateResponse,
    HealthResponse,
    MockExamRequest,
    MockExamResponse,
    QuizGenerateRequest,
    QuizQuestion,
    QuizSubmitRequest,
    QuizSubmitResponse,
    RevisionRequest,
    RevisionResponse,
    SourceRef,
    StudyPlanRequest,
    StudyPlanResponse,
    UploadResponse,
    WeakTopicsResponse,
)

__all__ = [
    "AskRequest",
    "AskResponse",
    "DocumentInfo",
    "EvaluateRequest",
    "EvaluateResponse",
    "HealthResponse",
    "MockExamRequest",
    "MockExamResponse",
    "QuizGenerateRequest",
    "QuizQuestion",
    "QuizSubmitRequest",
    "QuizSubmitResponse",
    "RevisionRequest",
    "RevisionResponse",
    "SourceRef",
    "StudyPlanRequest",
    "StudyPlanResponse",
    "UploadResponse",
    "WeakTopicsResponse",
]